apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec: 
  selector: 
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
       app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "pedroreckel/hello-go:v5"
          envFrom:  # Forma mais simples de importar todas as variáveis de ambiente.
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:  
              - mountPath: "/go/myfamily"
                name: config 
      
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items: 
              - key: members
                path: "family.txt"

          



        # Forma mais especifica de pegas as variáveis de ambiente:

          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME

          #   - name: AGE
          #     valueFrom:
          #      configMapKeyRef:
          #       name: goserver-env
          #       key: AGE
